{% set name = "opentelemetry-api" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_api-{{ version }}.tar.gz
  sha256: 2bbf29739fcef268c419e3bf1735566c2e7f81026c14bcc78b62a0b97f8ecf2f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - deprecated >=1.2.6
    - python >=3.7
    - setuptools >=16.0

test:
  imports:
    - opentelemetry
    - opentelemetry.context
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-api
  summary: OpenTelemetry Python API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - marcelotrevisani
