{% set name = "opentelemetry-api" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_api-{{ version }}.tar.gz
  sha256: 14a766548c8dd2eb4dfc349739eb4c3893712a0daa996e5dbf945f9da665da9d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
  run:
    - deprecated >=1.2.6
    - python >=3.8
    - setuptools >=16.0
    #  This should be able to be removed after 3.12 is released if there is a reliable API in importlib.metadata
    - importlib-metadata >=6.0.0,<7.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.context
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-api
  summary: OpenTelemetry Python API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - marcelotrevisani
