{% set name = "opentelemetry-api" %}
{% set version = "1.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_api-{{ version }}.tar.gz
  sha256: 48d167589134799093005b7f7f347c69cc67859c693b17787f334fbe8871279f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - deprecated >=1.2.6
    #  This should be able to be removed after 3.12 is released if there is a reliable API in importlib.metadata
    - importlib-metadata <8.8.0,>=6.0
    # - typing_extensions >=4.5.0

test:
  imports:
    - opentelemetry
    - opentelemetry.context
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-api
  summary: OpenTelemetry Python API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - marcelotrevisani
